/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LinyuEmpty: typeof import('./../components/LinyuEmpty.vue')['default']
    LinyuProvider: typeof import('./../components/LinyuProvider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIconButton: typeof import('./../components/SvgIconButton.vue')['default']
    ToolBar: typeof import('./../components/ToolBar.vue')['default']
  }
}

// For TSX support
declare global {
  const LinyuEmpty: typeof import('./../components/LinyuEmpty.vue')['default']
  const LinyuProvider: typeof import('./../components/LinyuProvider.vue')['default']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NBadge: typeof import('naive-ui')['NBadge']
  const NButton: typeof import('naive-ui')['NButton']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NInput: typeof import('naive-ui')['NInput']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NPopover: typeof import('naive-ui')['NPopover']
  const NScrollbar: typeof import('naive-ui')['NScrollbar']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIconButton: typeof import('./../components/SvgIconButton.vue')['default']
  const ToolBar: typeof import('./../components/ToolBar.vue')['default']
}